name: Github Action Demo
on: [push]

jobs:
  Explore-github-action:
    runs-on: ubuntu-latest
    steps:
    -  name: first step on action
       run: echo "this is first step of github-action"

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: install dependencies
        run: cd backend && npm i 

